# Generated by Django 5.1.3 on 2024-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_options_car_photo_car_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars/'),
        ),
    ]
